services:
  app:
    build: .
    ports:
      - "9000:9000"
    depends_on:
      - postgres
      - keycloak
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/javito
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      KEYCLOAK_URL: http://keycloak:8080
      RESOURCE_SERVER: http://keycloak:8080/realms/bulletin-board
      KEYCLOAK_REALM: bulletin-board
      KEYCLOAK_CLIENT_ID: spring-bulletin-board
      KEYCLOAK_CLIENT_SECRET: c9UotXvigAOObcNgIBLiAP2LtedQayVf
    networks:
      - my-network

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      - POSTGRES_DB=javito
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - my-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/javito
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=postgres

      - KC_DB_SCHEMA=public
      - KC_DB_INITIALIZE=true
      - KC_HTTP_ENABLED=true
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./themes:/opt/keycloak/themes
    command: ["start-dev"]
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - my-network

volumes:
  postgres_data:
  keycloak_data:

networks:
  my-network: